version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:4321"
    depends_on:
      - backend
    network_mode: host
    volumes:
      - ./frontend:/app
    environment:
      - PUBLIC_API_URL=http://localhost:4000

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    networks:
      - my-network
    volumes:
      - ./backend:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

networks:
  my-network:
